print("Гpyna 4")
text_file = open("/Users/kirillpetruska/Documents/python/students4.txt", "wt")
text_file.write("Данил Афганин, 0 балів\n")
text_file.write("Кристина Робкая, 0 балів\n")
text_file.write("Юрий Фролов, 0 балів\n")
text_file.write("Маша Иванова, 0 балів\n")
text_file.close()

print("Гpyna 5")
text_file = open("/Users/kirillpetruska/Documents/python/students5.txt", "wt")
text_file.write("Данил Лобанов, 0 балів\n")
text_file.write("Игорь Стеровой, 0 балів\n")
text_file.write("Юрий Долгополов, 0 балів\n")
text_file.write("Маша Забивная, 0 балів\n")
text_file.close()

print("Гpyna 6")
text_file = open("/Users/kirillpetruska/Documents/python/students6.txt", "wt")
text_file.write("Данил Дашкевич, 0 балів\n")
text_file.write("Кристина Филиппины, 0 балів\n")
text_file.write("Юрий Кроткополов, 0 балів\n")
text_file.write("Маша Омельянчук, 0 балів\n")
text_file.close()
 
